### ISSUE TITLE
Can't install in R4.0.2

### ISSUE THREAD

**Issue by pcantalupo** [dzhang32/dasper#2]
Hello,
I tried the following to install dasper but got errors:

```
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}

BiocManager::install("dasper")
```

which gave me this error:
```
Warning message:
package ‘dasper’ is not available (for R version 4.0.2) 
```

Then I tried 
```
BiocManager::install("dzhang32/dasper")
``` 
and got:
```
ERROR: dependency ‘megadepth’ is not available for package ‘dasper’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/dasper’
Error: Failed to install 'dasper' from GitHub:
  (converted from warning) installation of package ‘/var/folders/6b/fk6yw91n0gn9r5sr99yc88x5_r9zrk/T//Rtmp2WW3yy/file1165c7f39b482/dasper_1.1.6.tar.gz’ had non-zero exit status
```

I tried to install megadepth but got error that it is not available for R 4.0.2 `BiocManager::install("megadepth")`

```
Warning message:
package ‘megadepth’ is not available (for R version 4.0.2)
```

Not sure what to try next. Thank you

**Comment by dzhang32** [comment]
Hi @pcantalupo, 

Sorry for the delay in response, I missed this somehow. 

I believe this was due to a `megadepth` related issue that is now resolved. If I run `BiocManager::install("dzhang32/dasper")`, this currently installs successfully for me. 

Let me know if you are still having issues. 

Best, 

David
